version: '3.8'

services:
  app:
    build: 
      context: ../PROXY
      dockerfile: ../PROXY/Dockerfile
      args:
        # Update 'VARIANT' to pick an LTS version of Node.js: 16, 14, 12.
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: 14-buster
    # volumes:
    #   - ..:/workspace:cached

    # ports:
    #   - '5000'

    # Overrides default command so things don't shut down after the process ends.
    command: bash -c "cd workspace/ && npm run start"
    # network_mode: host
    networks:
        testing_net:
            ipv4_address: 172.28.1.1
  base:
    build: 
      context: ../BASE
      dockerfile: ../BASE/Dockerfile
      args:
        # Update 'VARIANT' to pick an LTS version of Node.js: 16, 14, 12.
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: 14-buster
    # volumes:
    #   - ..:/workspace:cached

    # ports:
    #   - '5000'

    # Overrides default command so things don't shut down after the process ends.
    command: bash -c "cd workspace/ && npm run start"
    # network_mode: host
    networks:
        testing_net:
            ipv4_address: 172.28.1.3
    
    # command: sleep infinity 


    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:db

    # Uncomment the next line to use a non-root user for all processes.
    # user: node

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  auth:
    build: 
      context: ../AUTH
      dockerfile: ../AUTH/Dockerfile
      args:
        # Update 'VARIANT' to pick an LTS version of Node.js: 16, 14, 12.
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: 14-buster
    # volumes:
    #   - ..:/workspace:cached

    # ports:
    #   - '5000'

    # Overrides default command so things don't shut down after the process ends.
    command: bash -c "cd workspace/ && npm run start"
    # network_mode: host
    networks:
        testing_net:
            ipv4_address: 172.28.1.4

  news:
    build: 
      context: ../NEWS
      dockerfile: ../NEWS/Dockerfile
      args:
        # Update 'VARIANT' to pick an LTS version of Node.js: 16, 14, 12.
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: 14-buster
    # volumes:
    #   - ..:/workspace:cached

    # ports:
    #   - '5000'

    # Overrides default command so things don't shut down after the process ends.
    command: bash -c "cd workspace/ && npm run start"
    # network_mode: host
    networks:
        testing_net:
            ipv4_address: 172.28.1.5          
  

  db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    command: mongod --port 5000
    # ports:
    #   - '5001:5001'
    # network_mode: host
    networks:
        testing_net:
            ipv4_address: 172.28.1.2

    # Uncomment to change startup options
    # environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: example
    #  MONGO_INITDB_DATABASE: your-database-here

    # Add "forwardPorts": ["27017"] to **devcontainer.json** to forward MongoDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  mongodb-data:



networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16

# networks:
#   dev:
#     driver: bridge
#     ipam:
#      config:
#        - subnet: 10.5.0.0/16
#          gateway: 10.5.0.1